// Converts raw catalogs (tools/raw/*.json, from ofrohn/d3-celestial, BSD-3) and
// the city-timezones package into compact plain-script data modules under src/data/.
// Run: npm run data   (raw files are fetched on demand if missing)
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const RAW = new URL('./raw/', import.meta.url);
const OUT = new URL('../src/data/', import.meta.url);
const BASE = 'https://cdn.jsdelivr.net/gh/ofrohn/d3-celestial/data/';
const FILES = ['stars.8.json', 'starnames.json', 'constellations.json', 'constellations.lines.json', 'messier.json', 'dsos.bright.json'];

mkdirSync(RAW, { recursive: true });
mkdirSync(OUT, { recursive: true });
for (const f of FILES) {
  const p = new URL(f, RAW);
  if (!existsSync(p)) {
    console.log('fetching', f);
    execSync(`curl -sSf -o "${p.pathname}" "${BASE}${f}"`);
  }
}
const raw = (f) => JSON.parse(readFileSync(new URL(f, RAW), 'utf8'));
const ra360 = (lon) => ((lon % 360) + 360) % 360;
const r = (x, d) => Number(x.toFixed(d));
const header = (what, src) => `// Generated by tools/prepare-data.mjs — do not edit by hand.\n// ${what}\n// Source: ${src}\n(function (root) {\n  root.SW = root.SW || {}; root.SW.DATA = root.SW.DATA || {};\n`;
const footer = `})(typeof globalThis !== 'undefined' ? globalThis : window);\n`;

// ---------------------------------------------------------------- stars
{
  const MAG_LIMIT = 6.5;
  const feats = raw('stars.8.json').features
    .filter((f) => f.properties.mag <= MAG_LIMIT)
    .sort((a, b) => a.properties.mag - b.properties.mag);
  const names = raw('starnames.json');
  const stars = [];
  const starNames = {};
  feats.forEach((f, i) => {
    const [lon, dec] = f.geometry.coordinates;
    const bv = f.properties.bv === '' ? 0.6 : Number(f.properties.bv);
    stars.push([r(ra360(lon), 3), r(dec, 3), r(f.properties.mag, 2), r(bv, 2)]);
    const n = names[String(f.id)];
    if (n && (n.name || n.bayer || n.flam)) {
      const e = { hip: f.id };
      if (n.name) e.name = n.name;
      if (n.bayer) e.bayer = n.bayer;
      if (n.flam) e.flam = n.flam;
      if (n.c) e.con = n.c;
      starNames[i] = e;
    }
  });
  writeFileSync(new URL('stars.js', OUT),
    header(`Stars to magnitude ${MAG_LIMIT} (${stars.length}). Each entry: [raDeg, decDeg, mag, B-V]. Sorted by magnitude.`,
      'HYG / Hipparcos via d3-celestial (BSD-3-Clause)') +
    `  root.SW.DATA.stars = ${JSON.stringify(stars)};\n` +
    `  // starNames[index] = {hip, name?, bayer?, flam?, con?} for stars with a proper name, Bayer or Flamsteed designation\n` +
    `  root.SW.DATA.starNames = ${JSON.stringify(starNames)};\n` + footer);
  console.log('stars', stars.length, 'named', Object.keys(starNames).length);
}

// ---------------------------------------------------------------- constellations
{
  const info = raw('constellations.json').features;
  const lines = raw('constellations.lines.json').features;
  const byId = Object.fromEntries(lines.map((l) => [l.id, l.geometry.coordinates]));
  const out = info.map((f) => ({
    id: f.id,
    name: f.properties.name,
    gen: f.properties.gen,
    ra: r(ra360(f.geometry.coordinates[0]), 2),
    dec: r(f.geometry.coordinates[1], 2),
    lines: (byId[f.id] || []).map((seg) => seg.map(([lon, dec]) => [r(ra360(lon), 2), r(dec, 2)])),
  })).sort((a, b) => a.id.localeCompare(b.id));
  writeFileSync(new URL('constellations.js', OUT),
    header('88 constellations (+ Serpens split): {id, name, gen (genitive), ra, dec (label position), lines: [[[ra,dec],...],...]}',
      'IAU boundaries / d3-celestial (BSD-3-Clause)') +
    `  root.SW.DATA.constellations = ${JSON.stringify(out)};\n` + footer);
  console.log('constellations', out.length);
}

// ---------------------------------------------------------------- deep-sky objects
{
  const COMMON = {
    M1: 'Crab Nebula', M6: 'Butterfly Cluster', M7: "Ptolemy's Cluster", M8: 'Lagoon Nebula', M11: 'Wild Duck Cluster',
    M13: 'Great Hercules Cluster', M16: 'Eagle Nebula', M17: 'Omega Nebula', M20: 'Trifid Nebula', M22: 'Sagittarius Cluster',
    M24: 'Sagittarius Star Cloud', M27: 'Dumbbell Nebula', M31: 'Andromeda Galaxy', M33: 'Triangulum Galaxy', M42: 'Orion Nebula',
    M43: "De Mairan's Nebula", M44: 'Beehive Cluster', M45: 'Pleiades', M51: 'Whirlpool Galaxy', M57: 'Ring Nebula',
    M63: 'Sunflower Galaxy', M64: 'Black Eye Galaxy', M76: 'Little Dumbbell Nebula', M81: "Bode's Galaxy", M82: 'Cigar Galaxy',
    M87: 'Virgo A', M97: 'Owl Nebula', M101: 'Pinwheel Galaxy', M104: 'Sombrero Galaxy', M110: 'Edward Young Star',
    'NGC 869': 'Double Cluster (h Persei)', 'NGC 884': 'Double Cluster (χ Persei)', 'NGC 5139': 'Omega Centauri',
    'NGC 104': '47 Tucanae', 'NGC 3372': 'Carina Nebula', 'NGC 2244': 'Rosette Nebula cluster', 'NGC 2264': 'Christmas Tree Cluster',
    'Cr 399': 'Coathanger', 'Cr 256': 'Coma Star Cluster', 'C 41': 'Hyades', 'IC 2602': 'Southern Pleiades',
    'IC 2391': 'Omicron Velorum Cluster', 'NGC 292': 'Small Magellanic Cloud', 'PGC 17223': 'Large Magellanic Cloud',
    'NGC 6231': 'Northern Jewel Box', 'NGC 3532': 'Wishing Well Cluster', 'NGC 2516': 'Southern Beehive', 'NGC 2362': 'Tau Canis Majoris Cluster',
    'NGC 2451': 'Puppis cluster', 'Cr 140': 'Collinder 140',
  };
  delete COMMON.M110; // (no widely used common name)
  const TYPE = { s: 'galaxy', e: 'galaxy', i: 'galaxy', sd: 'galaxy', g: 'galaxy', oc: 'open cluster', gc: 'globular cluster', pn: 'planetary nebula', snr: 'supernova remnant', sfr: 'nebula', en: 'nebula', rn: 'reflection nebula', dn: 'dark nebula', pos: 'position', bn: 'nebula' };
  const dim = (s) => { if (!s) return 0; const m = String(s).split('x').map(Number); return r(Math.max(...m) || 0, 1); };
  const out = [];
  const seen = new Set();
  for (const f of raw('messier.json').features) {
    const p = f.properties;
    const [lon, dec] = f.geometry.coordinates;
    out.push({ id: p.name, name: COMMON[p.name] || p.alt || '', desig: p.desig, type: TYPE[p.type] || p.type, mag: p.mag, ra: r(ra360(lon), 3), dec: r(dec, 3), size: dim(p.dim) });
    seen.add(p.desig);
    seen.add(p.name.replace('M', 'M '));
  }
  for (const f of raw('dsos.bright.json').features) {
    const p = f.properties;
    if (seen.has(f.id) || p.type === 'pos') continue;
    const [lon, dec] = f.geometry.coordinates;
    out.push({ id: f.id, name: COMMON[f.id] || '', desig: '', type: TYPE[p.type] || p.type, mag: p.mag, ra: r(ra360(lon), 3), dec: r(dec, 3), size: dim(p.dim) });
  }
  writeFileSync(new URL('dso.js', OUT),
    header('Deep-sky objects: all 110 Messier objects plus bright non-Messier showpieces. {id, name (common), desig (NGC), type, mag, ra, dec, size (arcmin, major axis)}',
      'd3-celestial (BSD-3-Clause)') +
    `  root.SW.DATA.dsos = ${JSON.stringify(out)};\n` + footer);
  console.log('dsos', out.length);
}

// ---------------------------------------------------------------- cities
{
  const { cityMapping } = require('city-timezones');
  const best = new Map();
  for (const c of cityMapping) {
    if (!c.timezone || c.pop < 200000) continue;
    const key = `${c.city}|${c.iso2}`;
    if (!best.has(key) || best.get(key).pop < c.pop) best.set(key, c);
  }
  const cities = [...best.values()].sort((a, b) => b.pop - a.pop)
    .map((c) => [c.city, c.country, r(c.lat, 2), r(c.lng, 2), c.timezone]);
  writeFileSync(new URL('cities.js', OUT),
    header(`${cities.length} cities with population ≥ 200,000, sorted by population. Each entry: [name, country, lat, lon, IANA time zone]`,
      'city-timezones npm package (MIT)') +
    `  root.SW.DATA.cities = ${JSON.stringify(cities)};\n` + footer);
  console.log('cities', cities.length);
}
